### ISSUE TITLE
Not working for me

### ISSUE THREAD

**Issue by JustaguyPY** [surenjanath/Spotify-Song-Downloader-PyQt5#10]
Version: 2.1 (python)
I have this error for all songs, tried whit vpn and in other playlist
[*] Error Status Code :  division by zero
[*] Trying to using v2 method...
[*] URL :  https://api.spotifydown.com/download/1EoThnDm6kQfB2idIfR30n
[*] FileName :  C:\Users\Matu\Music\Spotify Downloader\music\playlist9  Matu\Your Love Is My Drug 8 Bit Slowed - just valery.mp3
Error [Errno 2] No such file or directory: 'C:\\Users\\Matu\\Music\\Spotify Downloader\\music\\playlist9  Matu\\Your Love Is My Drug 8 Bit Slowed - just valery.mp3'
[*] Error Status Code :  division by zero

**Comment by surenjanath** [comment]
works now. download the new version.
