### ISSUE TITLE
Download Folder Changes

### ISSUE THREAD

**Issue by wesux** [surenjanath/Spotify-Song-Downloader-PyQt5#12]
The download folder does not stay the same. Everythime the program runs it puts the downloads in a folder called music in random places each time.

**Comment by surenjanath** [comment]
Hi I'll look at it next couple hours

**Comment by surenjanath** [comment]
okay im kinda trying to understand what you mean. it will only create 1 folder with subfolders . each playlist will be in a subfolder

**Comment by wesux** [comment]
Issue was reported incorrectly.
