### ISSUE TITLE
not download all songs

### ISSUE THREAD

**Issue by hhoangnpm** [surenjanath/Spotify-Song-Downloader-PyQt5#15]
i tried to download a 173 songs playlist (https://open.spotify.com/playlist/3DOgY49uE7KXnOegoMAthm?si=54a654324bdd4d28) but it only downloaded 49 of them (it said scraping completed)
![image](https://github.com/surenjanath/Spotify-Song-Downloader-PyQt5/assets/149093750/7a58cd39-7516-4bce-b5e2-e9f56cbf2eae)

**Comment by ui6s** [comment]
same problem here.
