### ISSUE TITLE
Need to fix bugs // Oct. 28, 2023

### ISSUE THREAD

**Issue by zeikkux** [surenjanath/Spotify-Song-Downloader-PyQt5#16]
Bugs:
1. It download songs in order right? but I noticed it skipped downloading some songs.
2. Scrapping completed. It downloads few songs. for example: My playlist have 50 songs, it downloaded 18 of them.
3. Add the metadata like cover image and release date in the downloaded songs.
4. Too small and can't be resized user interface.

Need Improvements (Optional):
1. UI theme (apple/iphone theme preferred)

Overall, nice app. It works fine but needs further improvements. thanks

**Comment by iamtim250** [comment]
I'm seeing similar issues, randomly stops, sometimes says completed even though there's more to go. Seems to restart and not make duplicate copies so thats good.

**Comment by surenjanath** [comment]
Fixed.
