### ISSUE TITLE
Randomly stops downloading songs

### ISSUE THREAD

**Issue by ui6s** [surenjanath/Spotify-Song-Downloader-PyQt5#18]
It works well, but it randomly stops downloading, I have a 259 song playlist and it stopped at 29 songs.

**Comment by XnvX00** [comment]
same for me
but i had 50 songs to download and it crashed on 16th
maybe will be cool to make a log report file and then we will send you what's the problem

**Comment by wesux** [comment]
Only downloads about half of the playlist.

**Comment by surenjanath** [comment]
it should work now. try again and reopen issue if still happening.
