### ISSUE TITLE
Anteupplaya on  yt

### ISSUE THREAD

**Issue by Anteupplaya** [surenjanath/Spotify-Song-Downloader-PyQt5#2]
![Screenshot 2023-08-05 143131](https://github.com/surenjanath/Spotify-Song-Downloader-PyQt5/assets/141522063/bd911003-d420-4f2d-b0bb-b8816aea3264)

**Comment by Anteupplaya** [comment]
its now giving me a new error

**Comment by surenjanath** [comment]
okay so the access deny means there's an app or av that's holding it back from saving the file

**Comment by Anteupplaya** [comment]
Okay I ran it as administrator and it gave me the original erro
![Screenshot 2023-08-05 145059](https://github.com/surenjanath/Spotify-Song-Downloader-PyQt5/assets/141522063/a12b1115-7113-4038-b9d0-bd17fd6269d0)
r

**Comment by surenjanath** [comment]
paste the playlist here

**Comment by Anteupplaya** [comment]
https://open.spotify.com/playlist/5Yr3eK6N4bfCWg9j4QBRAw?si=ce30cfed09fc4ff7

**Comment by surenjanath** [comment]
![image](https://github.com/surenjanath/Spotify-Song-Downloader-PyQt5/assets/42503383/3e4c774a-39ae-4f2f-8379-75a0a885e2a6)

it works fine on my end. 
Most Likely you'll need to try a vpn

**Comment by Anteupplaya** [comment]
can you recommend a free vpn?

**Comment by surenjanath** [comment]
tbh i've never used a vpn haha :( sorry man

**Comment by Anteupplaya** [comment]
damn...is there maybe a setting i can change on the device that may fix the issue?

**Comment by surenjanath** [comment]
the old version use to work or you're now using this ?

**Comment by Anteupplaya** [comment]
im now using this. i have a huge list and saw your yt short

**Comment by surenjanath** [comment]
Try this temporarily and if it not work. delete 
https://protonvpn.com/free-vpn/pc
their mobile app is really good so i gues their pc version should be good too

**Comment by Anteupplaya** [comment]
lol. i just installed that by myself also good news. it is working
thanks for your help, i cant believe how nice you were! id suggest on the github saying you may need a vpn. if you dont have one use protonvpn.

**Comment by Anteupplaya** [comment]
![image](https://github.com/surenjanath/Spotify-Song-Downloader-PyQt5/assets/141522063/81fd398b-7b78-4749-b548-fe598cbaefaf)
btw heres proof its working

**Comment by surenjanath** [comment]
okayyy greaet !!! so it's working i now will close this :) 
thanks for suggestion will add it in a few

**Comment by Anteupplaya** [comment]
goodbye!
