### ISSUE TITLE
hope that the info the song could be added when downloading

### ISSUE THREAD

**Issue by dhqdbb** [surenjanath/Spotify-Song-Downloader-PyQt5#3]
hope that the info the song could be added when downloading

**Comment by surenjanath** [comment]
added in v2.1

**Comment by dhqdbb** [comment]
thanks a lot， nice app








邓皓谦&nbsp;GARY
***@***.***

对外经济贸易大学

---Original---
From: "Surenjanath ***@***.***&gt;
Date: Thu, Aug 17, 2023 09:44 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [surenjanath/Spotify-Song-Downloader-PyQt5] hope that the infothe song could be added when downloading (Issue #3)




 
added in v2.1

**Comment by surenjanath** [comment]
thans man
