### ISSUE TITLE
Set download speed

### ISSUE THREAD

**Issue by wesux** [surenjanath/Spotify-Song-Downloader-PyQt5#6]
Will Spotify ban your account for using this? I know other downloaders have a 1x speed so it does not raise any red flags.

**Comment by surenjanath** [comment]
Tbh it doesnt use your spotify in any way. I think the endpoint uses youtube to download the songs. I just utilize the api endpoint :)

**Comment by surenjanath** [comment]
this does not raise any downloading issues as it does not link to you spotify account in any way. so this can be closed :)
