### ISSUE TITLE
not working 

### ISSUE THREAD

**Issue by JustaguyPY** [surenjanath/Spotify-Song-Downloader-PyQt5#9]
In both versions (python and windows) it stays at 'title' and the songs are never downloaded 
![image](https://github.com/surenjanath/Spotify-Song-Downloader-PyQt5/assets/138535056/9f624ee7-ce7d-4dc0-abea-cac42584b702)

**Comment by surenjanath** [comment]
Hi It still works, 
try using a vpn 

see image  


![image](https://github.com/surenjanath/Spotify-Song-Downloader-PyQt5/assets/42503383/8cf10f40-a31a-42b5-9fd7-595bced6e4ac)

**Comment by JustaguyPY** [comment]
now i have this error 
![image](https://github.com/surenjanath/Spotify-Song-Downloader-PyQt5/assets/138535056/dc94c0b7-e400-474b-b5a2-a55e2a354c9d)

**Comment by JustaguyPY** [comment]
Installed pysocks but now stays in 'title' again

**Comment by JustaguyPY** [comment]
> Hi It still works, try using a vpn
> 
> see image
> 
> ![image](https://user-images.githubusercontent.com/42503383/274454602-8cf10f40-a31a-42b5-9fd7-595bced6e4ac.png)

thanks
